steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/configmap-secrets-kube-file:1.1', '.']
  timeout: 180s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/configmap-secrets-kube-file:1.1']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=secrets/secrets.json.enc
  - --plaintext-file=secrets/secrets.json
  - --location=global
  - --keyring=build-keyrin
  - --key=demo-key
- name: 'gcr.io/cloud-builders/kubectl'
  #args: ['create', 'secret', 'generic', 'password', '--from-literal=PASSWORD=$$PASSWORD', '-o yaml', '--dry-run', '|', 'kubectl', 'replace', '--filename=-' ]
  args: ['create', 'secret', 'generic', 'access_secrets', '--from-file=secrets/secrets.json']
  secretEnv: ['PASSWORD']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cloud-build-example'
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cloud-build-example'
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - configmap-secrets-kube-file
  - web=gcr.io/$PROJECT_ID/configmap-secrets-kube-file:1.1
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cloud-build-example'
