apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: configmap-secrets-kube-file
  name: configmap-secrets-kube-file
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configmap-secrets-kube-file
  template:
    metadata:
      labels:
        app: configmap-secrets-kube-file
    spec:
      containers:
      - name: web
        image: gcr.io/kube-teach1/configmap-secrets-kube-file:v1.1
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        volumeMounts:
          - name: access-secrets
            mountPath: /usr/src/site/secret
      volumes:
      - name: access-secrets
        secret:
          secretName: access-secrets

